// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"ib30ned6j3","name":"userData-MobileHub-765262059","description":"Contains user information ","endpoint":"https://ib30ned6j3.execute-api.us-west-1.amazonaws.com/Development","region":"us-west-1","paths":["/userData","/userData/test","/userData/123"]}],
    'aws_cognito_identity_pool_id': 'us-west-2:9c446c8e-9d7c-40cf-b576-0845ae083d61',
    'aws_cognito_region': 'us-west-2',
    'aws_mobile_analytics_app_id': '86cd0880afe24f7cb55966e5200d88e0',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'a28e1ea9-cc7e-4cba-ac80-9f49096e305f',
    'aws_project_name': 'mani.me.v1.0.2',
    'aws_project_region': 'us-west-1',
    'aws_resource_name_prefix': 'manimev-mobilehub-1668666312',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'manimev-userfiles-mobilehub-1668666312',
    'aws_user_files_s3_bucket_region': 'us-west-1',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-west-2_D5MHfdMAY',
    'aws_user_pools_web_client_id': '425tvq1f46568m8kn9ifi1q56i',
}

export default awsmobile;
